### ISSUE TITLE
Is there a working/stable example of the lambda/serverless version of this?

### ISSUE THREAD

**Issue by iDVB** [johnagan/slack-devkit#1]
The docs reference serverless.yml but I don't see it anywhere in the repo.
Is this project complete yet?

**Comment by johnagan** [comment]
Good catch! I had it in the example folder and accidentally ignored it last push. Here ya go:

[serverless.example.yml](https://github.com/johnagan/slack-devkit/blob/master/examples/serverless.example.yml)

[lambda.js](https://github.com/johnagan/slack-devkit/blob/master/examples/lambda.js)
