### ISSUE TITLE
Serverless + Lambda single-workspace app

### ISSUE THREAD

**Issue by SteveNewhouse** [johnagan/slack-devkit#2]
Hello there,

I'm trying to get a single-workspace Lambda + Serverless app up and running but I'm running into issues that appear to be related to missing data in the datastore.  Do I even need the datastore for this type of setup?  Anything I can do to work around this?

Thank you,
Steve

**Comment by SteveNewhouse** [comment]
Error is as follows:
{"errorMessage":"Cannot read property 'Item' of undefined","errorType":"TypeError","stackTrace":["query.then (/var/task/node_modules/slack-devkit/dist/datastore/dynamodb.js:34:56)","<anonymous>","process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}

**Comment by johnagan** [comment]
You do need the datastore to support OAuth.

**Comment by SteveNewhouse** [comment]
I've gotten it to actually write the config to the dynamo db instance post-install, but upon sending a sample slash command I get the same error above.

**Comment by SteveNewhouse** [comment]
Pardon my naivete on this--- kinda fumbling my way forward... here's what my handler looks like:

```
const { SIGNING_SECRET, CLIENT_ID, CLIENT_SECRET, SCOPE, TABLE_NAME } = process.env;

const Slack = require('slack-devkit');

// Configure express with the Slack App settings
const { lambda } = new Slack({
	scope: SCOPE,
	client_id: CLIENT_ID,
	client_secret: CLIENT_SECRET,
	signing_secret: SIGNING_SECRET,
	datastore: TABLE_NAME
});

exports.slackHandler = lambda((slack, context, callback) => {
	// route events based on the payload
	if (slack.is('app_installed'))
		return sendInstallMessage(slack, context);

	if (slack.is('slash_command'))
		return handleSlashCommand(slack, context);
});

function sendInstallMessage(slack, context) {
	// the slack object contains information about the request
	// and the workspace's authentication information
	const { data, app_url } = slack;

	// open the Slack client to the App Home
	const redirect = () => context.fail(app_url);

	// construct a welcome message to the installer
	const message = {
		channel: data.installer_user.app_home,
		text: 'Thanks for installing me :bow:'
	};

	// Make an authenticated request to the Slack API
	return slack.api('chat.postMessage', message).then(redirect)
}

function handleSlashCommand(slack, context) {
	console.log("slack: " + JSON.stringify(slack));
	const message = {
		text: 'Hello :bow:'
	};

	// Make an authenticated request to the Slack API
	return slack.reply(message);
}
```

**Comment by johnagan** [comment]
Hmm.. feels like the error might be related to looking up the config in Dynamo. Maybe the slash command is coming from a different workspace?

**Comment by SteveNewhouse** [comment]
I logged an incoming request and the team_id does match what is in dynamo

**Comment by mtb-xt** [comment]
I think I'm having the same issue. It's not clear how to make the app store the config in datastore post install, when using it as a single workspace app on lambda.

I'm getting this error, and nothing is created in the datastore. 

```{
    "errorMessage": "Cannot read property 'Item' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "query.then (/var/task/node_modules/slack-devkit/dist/datastore/dynamodb.js:34:56)",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}
```

**Comment by johnagan** [comment]
I'll look into the Single-Workspace in Lambda scenario and see what's up

**Comment by powderham** [comment]
👍 I've also got this issue.
Let us know how we can help @johnagan

**Comment by johnagan** [comment]
not discrediting the issue, but for my own curiosity - why use single-workspace mode?

**Comment by powderham** [comment]
I was doing it just because I was tinkering around, so wanted to keep it under wraps until I knew I could distribute it. 

I've since made it distributable, but still have the issue.

**Comment by johnagan** [comment]
Gotcha. And you are deploying with serverless?

**Comment by powderham** [comment]
Correct. I'm wondering if it's something to do with the redirect_uri, since there is nothing in my dynamo db. I assume this is required to be set to my lamdba endpoint, right?

**Comment by johnagan** [comment]
You set it here:
https://github.com/johnagan/slack-devkit/blob/master/examples/serverless.example.yml#L37

**Comment by powderham** [comment]
I've done it but I still get the same error. My endpoint has `/dev/slack` after the `.amazonaws.com/`.
 
Was this something intentionally omitted from an example, or should I be including it in my set up. I can't see any activity on CloudWatch.

**Comment by johnagan** [comment]
It's hard to diagnose without all the info. 9x out of 10 it's something with API gateway not being configured correctly, which is why I point to serverless.js to deploy and configure everything.

**Comment by powderham** [comment]
Agreed. I'm letting serverless do the deploy/config, so it must be a problem with the values i've stored somewhere.

Interestingly if I visit the redirect_uri myself, I can authorise the bot, and then get stopped told that app_home is undefined in the below function:

```
function sendInstallMessage(slack, context) {
  // the slack object contains information about the request
  // and the workspace's authentication information
  const { data, app_url } = slack

  // open the Slack client to the App Home
  const redirect = () => context.fail(app_url)

  // construct a welcome message to the installer
  const message = {
    channel: data.installer_user.app_home,   <---- here
    text: 'Thanks for installing me :bow:'
  }

  // Make an authenticated request to the Slack API
  return slack.api('chat.postMessage', message).then(redirect)
}
```

**Comment by johnagan** [comment]
> app_home is undefined

Ah ha! This I know - This example uses the [Workspace App](https://api.slack.com/workspace-apps-preview) model, which supports `app_home` to DM users.

**Comment by mtb-xt** [comment]
@johnagan I'm using single-workspace mode because the app is going to be for internal use only. I've used serverless template to deploy. From the manual it is unclear that in single mode I have to open the redirect url myself to authorize the app. After I did it, I've got the same error as @powderham above. Maybe it would be better to have a more complete and "idiot-proof" user guide for lambda deploys... (especially what types of tokens are needed, when and in which mode they are needed and when not..)  <_<

**Comment by mtb-xt** [comment]
ok I've managed to install the app by hardcoding the channel to write to, but I'm still getting ``` "errorMessage":"Cannot read property 'Item' of undefined" ``` - even though there is something in dynamodb now -_-

**Comment by SteveNewhouse** [comment]
☝️ This is where I got to as well.  Whatever it's trying to fetch, it's not finding it (even though what is there was written by the app post-successful-OAuth.  The team ID from the incoming slash command matches the key for the dynamo record.

**Comment by mtb-xt** [comment]
With a couple of strategically placed `console.log()`s I've managed to get the id from the dynamodb request - it equals to the stored item in dynamodb.

I also got this error message out of the app:
```
{"errorMessage":"Cannot destructure property `access_token` of 'undefined' or 'null'.",
"errorType":"TypeError",
"stackTrace":["Request.api (/var/task/node_modules/slack-devkit/dist/core/request.js:127:58)",
"Request.reply (/var/task/node_modules/slack-devkit/dist/core/request.js:159:21)",
"handleSlashCommand (/var/task/index.js:52:15)",
"exports.slackHandler.lambda (/var/task/index.js:23:10)",
"done (/var/task/node_modules/slack-devkit/dist/server/lambda.js:11:28)",
"<anonymous>",
"process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}
```

I've also looked at `settings` object, and it has `access_token` set. Maybe it's because of my added logging, but I can't figure out anything else.

**Comment by powderham** [comment]
Hey John,

I too am having the missing item issue:

My constructor for dynamo looks like the following:
```
 Key: { id: 'T3PK8K7UP' }, TableName: 'Workspaces' } constructor {
  options: { attrValue: 'S8' },
  service:
   constructor {
     config:
      constructor {
        credentials: [Object],
        credentialProvider: [Object],
        region: 'us-east-1',
        logger: null,
        apiVersions: {},
        apiVersion: null,
        endpoint: 'dynamodb.us-east-1.amazonaws.com',
        httpOptions: [Object],
        maxRetries: undefined,
        maxRedirects: 10,
        paramValidation: true,
        sslEnabled: true,
        s3ForcePathStyle: false,
        s3BucketEndpoint: false,
        s3DisableBodySigning: true,
        computeChecksums: true,
        convertResponseTypes: true,
        correctClockSkew: false,
        customUserAgent: null,
        dynamoDbCrc32: true,
        systemClockOffset: 0,
        signatureVersion: 'v4',
        signatureCache: true,
        retryDelayOptions: {},
        useAccelerateEndpoint: false,
        clientSideMonitoring: false },
     isGlobalEndpoint: false,
     endpoint:
      constructor {
        protocol: 'https:',
        host: 'dynamodb.us-east-1.amazonaws.com',
        port: 443,
        hostname: 'dynamodb.us-east-1.amazonaws.com',
        pathname: '/',
        path: '/',
        href: 'https://dynamodb.us-east-1.amazonaws.com/' },
     _events: { apiCallAttempt: [Array], apiCall: [Array] },
     MONITOR_EVENTS_BUBBLE: [Function],
     CALL_EVENTS_BUBBLE: [Function],
     _clientId: 1 },
  attrValue: 'S8' }
```

My lay persons view looks like it's missing the specifics for my particular resource. Is there anything you notice missing in there?

**Comment by johnagan** [comment]
I see the problem... I built this against the new Workspace App token model and need to update it to support the User Token App model. I'll start working on it

**Comment by mtb-xt** [comment]
> I see the problem... I built this against the new Workspace App token model and need to update it to support the User Token App model. I'll start working on it

@johnagan Could you show how to configure the app to use the Workspace App token? I've tried using it and still got the same error.. ?

**Comment by powderham** [comment]
@johnagan - I've got the day off tomorrow, if you want me to take a look at it. 
Happy to have a call today to discuss.

**Comment by msimperi** [comment]
See #4. I think it might be related to error you see. The "data" is not actually returned at all from the callback of DynamoDB.

**Comment by johnagan** [comment]
version `1.2.3` should have this resolved. Thanks!
