### ISSUE TITLE
SlackDevKit not returning lambda object.

### ISSUE THREAD

**Issue by powderham** [johnagan/slack-devkit#3]
Hi John,

First let me express my gratitude for you creating this. 
I am trying to set up lambda functions leveraging slack-devkit but seem to be falling at the first hurdle.

When trying to access lambda on the SlackDevKit instance, I am told the module isn't found.

```
{
    "code": "MODULE_NOT_FOUND"
}
```

I am constructing my instance in the following way:

```
"use strict";
const { SIGNING_SECRET, CLIENT_ID, CLIENT_SECRET, TABLE_NAME } = process.env;
// Include the serverless-slack bot framework
const Slack = require("slack-devkit");
const slack = new Slack({
  scope: "bot,commands,incoming-webhook",
  client_id: CLIENT_ID,
  client_secret: CLIENT_SECRET,
  signing_secret: "e1ca1929414648c9f346fb4eee2cd32d",
  datastore: TABLE_NAME
});

const { lambda } = slack;
```

Note, I have pulled the assignment of lambda out of the creation of the new instance for debugging purposes.

I have been able to see that an instance is created, but only with settings:

```
SlackDevKit {
  settings:
   { scope: 'bot,commands,incoming-webhook',
     client_id: '12565465----.441023----',                        // Obfuscated for this issue
     client_secret: '50c85ed5148aa8--------',
     signing_secret: 'e1ca1929414648c9--------,
     datastore: 'Teams' } }
```

**Comment by johnagan** [comment]
Are you using the serverless.example.yml to configure Lamba?

**Comment by powderham** [comment]
Thanks for the super fast response.

I am indeed. On second thought, I haven't configured a DynamoDB, so the resource just points to `arn:aws:dynamodb:us-east-1:*:*`. Should this be the case, or is it something I need to configure.

This is also my first foray in to Lambda functions, so I am a bit unsure of which parts of the yml require updating and which don't.

Edit: I'm looking to build a functional bot on top of this, so will be happy to contribute back in the codebase/docs.

**Comment by johnagan** [comment]
Gotcha! If you're using OAuth, then you'll need a database to store tokens. For AWS I wrote the DynamoDB connector. 

The other big kicker with Lambda/Slack is API Gateway needs to be configured ever so perfectly to handle all of Slack's various payloads. The [serverless.example.yml](https://github.com/johnagan/slack-devkit/blob/master/examples/serverless.example.yml) will set all that up for you if you use [serverless.js](https://serverless.com/)

**Comment by powderham** [comment]
Ok, pleased we're on the hunt.

Perhaps I can contribute back some handler for when a connection to the db cannot be created, or something similar.

In setting up my db I'm being asked for the primary key, what does slack-devkit persist to the db (so I can infer from it what my primary key should be..)

Edit: Looking at the source code it seems to be `id`, but would appreciate confirmation.
Edit: Turns out the table creation is all handled by the deploy command. Closing issue now. Thanks for the help.
