### ISSUE TITLE
DynamoDb callback configuration error

### ISSUE THREAD

**Issue by msimperi** [johnagan/slack-devkit#4]
https://github.com/johnagan/slack-devkit/blob/b659139cbd9a4e0232a64174a6686b896be22858/src/datastore/dynamodb.ts#L52-L56

Should callback have data also as parameter? Now only err is a parameter.

**Comment by johnagan** [comment]
Good catch! I must have broken it when I switch this file to TS.

**Comment by johnagan** [comment]
version `1.2.3` should have this resolved. Thanks!
