### ISSUE TITLE
lambda, silent response

### ISSUE THREAD

**Issue by mogadanez** [johnagan/slack-devkit#6]
How to make /slash command  without  any response?
lambda from examples returns "null" string back to slack

I tried  manually 
            return callback(null, {
                statusCode: 200               
            })
            return callback(null, 200)
            return callback(null)

it always print it into slack.

**Comment by johnagan** [comment]
try `callback("")`

**Comment by mogadanez** [comment]
then empty quotes in slack appears,
""

maybe something wrong with integration responses in sample serverless.yml config?

**Comment by johnagan** [comment]
try using `context.success()`
